//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFunctionsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFunction
    {
        public CustomFunction()
        {
            this.CustomFunctionAttributes = new HashSet<CustomFunctionAttribute>();
        }
    
        public string DB { get; set; }
        public int FunctionID { get; set; }
        public string FunctionName { get; set; }
        public string SourceCode { get; set; }
        public int CRFVersionID { get; set; }
        public string Lang { get; set; }
        public System.DateTime Created { get; set; }
        public System.DateTime Updated { get; set; }
        public Nullable<System.DateTime> ServerSyncDate { get; set; }
        public Nullable<int> SourceObjectID { get; set; }
        public Nullable<System.DateTime> SourceCopyTime { get; set; }
        public string OID { get; set; }
        public Nullable<System.DateTime> UpdatedAfterSourceCopy { get; set; }
        public bool IsDraft { get; set; }
    
        public virtual ICollection<CustomFunctionAttribute> CustomFunctionAttributes { get; set; }
    }
}
