//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFunctionsWebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFunctionAttribute
    {
        public CustomFunctionAttribute()
        {
            this.MethodCalls = new HashSet<MethodCall>();
        }
    
        public string DB { get; set; }
        public int FunctionID { get; set; }
        public int ID { get; set; }
        public string SHA256 { get; set; }
    
        public virtual ICollection<MethodCall> MethodCalls { get; set; }
        public virtual CustomFunction CustomFunction { get; set; }
    }
}
