//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.CustomFunctionWebApp_001.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomFunctionSummary
    {
        public string DB { get; set; }
        public int FunctionID { get; set; }
        public string FunctionName { get; set; }
        public Nullable<int> MethodCallCount { get; set; }
    }
}
