// <auto-generated />
namespace CustomFunctionAnalysis_003.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class BaselineTables : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaselineTables));
        
        string IMigrationMetadata.Id
        {
            get { return "201706270003307_BaselineTables"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
