//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CustomFunctionWebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MethodCallArgument
    {
        public int ID { get; set; }
        public string ArgumentValue { get; set; }
        public int ArgumentIndex { get; set; }
        public Nullable<int> MethodCall_ID { get; set; }
    
        public virtual MethodCall MethodCall { get; set; }
    }
}
